# Template para secrets - NÃO COMMITAR COM VALORES REAIS
# Copie para application-secrets-local.yml e configure valores reais

spring:
  datasource:
    username: ${DB_USERNAME:your_db_username}
    password: ${DB_PASSWORD:your_db_password}
  
  data:
    redis:
      password: ${REDIS_PASSWORD:your_redis_password}

firebase:
  project-id: ${FIREBASE_PROJECT_ID:your-firebase-project}
  credentials-path: ${FIREBASE_CREDENTIALS:./config/firebase-credentials.json}

vynlo:
  ssl:
    key-store-password: ${SSL_KEYSTORE_PASSWORD:your_keystore_password}
    trust-store-password: ${SSL_TRUSTSTORE_PASSWORD:your_truststore_password}
  
  backup:
    s3-bucket: ${BACKUP_S3_BUCKET:your-backup-bucket}

# JWT Secret
jwt:
  secret: ${JWT_SECRET:your-jwt-secret-key-minimum-256-bits}
  expiration: ${JWT_EXPIRATION:86400000}

# Encryption keys
encryption:
  key: ${ENCRYPTION_KEY:your-encryption-key}
  salt: ${ENCRYPTION_SALT:your-encryption-salt}