spring:
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutos padrão
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "vynlo:cache:"
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2000ms
        shutdown-timeout: 100ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
  endpoint:
    caches:
      enabled: true
  metrics:
    cache:
      instrument: true
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.cache: DEBUG
    com.vynlotaste.service: DEBUG
    org.springframework.data.redis: WARN