spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 10000

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379
      database: 15 # Base separada para testes
      timeout: 1000ms

  cache:
    type: simple # Cache em memória para testes
    redis:
      time-to-live: 60000 # 1 minuto para testes

firebase:
  project-id: vynlo-taste-test
  credentials-path: ./config/firebase-test.json

vynlo:
  features:
    new-ui: false
    analytics: false
    beta-features: false
  
  rate-limit:
    requests-per-minute: 10000 # Sem limite para testes
    burst-capacity: 1000
  
  cors:
    allowed-origins:
      - "*"
    allowed-methods:
      - "*"
    allowed-headers: "*"
    allow-credentials: true

logging:
  level:
    com.vynlotaste: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.testcontainers: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: never