# Configurações de Segurança para Produção
security:
  jwt:
    secret: ${JWT_SECRET:your-super-secret-jwt-key-change-in-production}
    expiration: 86400000 # 24 horas
    refresh-expiration: 604800000 # 7 dias
  
  firebase:
    project-id: ${FIREBASE_PROJECT_ID:vynlo-taste}
    service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:classpath:firebase-service-account.json}
  
  rate-limiting:
    enabled: true
    default-limit: 1000 # requisições por hora por IP
    auth-limit: 5 # tentativas de login por minuto
    admin-limit: 100 # requisições admin por hora
  
  cors:
    allowed-origins:
      - https://vynlotaste.com
      - https://*.vynlotaste.com
      - http://localhost:3000 # apenas dev
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Requested-With
      - Accept
      - Origin
    max-age: 3600
  
  headers:
    content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:; frame-ancestors 'none';"
    x-frame-options: DENY
    x-content-type-options: nosniff
    x-xss-protection: "1; mode=block"
    strict-transport-security: "max-age=31536000; includeSubDomains; preload"

# Logging de Segurança
logging:
  level:
    com.vynlotaste.config: DEBUG
    SECURITY_AUDIT: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{requestId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{requestId}] %logger{36} - %msg%n"
  file:
    name: logs/security-audit.log
    max-size: 100MB
    max-history: 30

# Actuator Security
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN
  security:
    enabled: true