spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:20}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      leak-detection-threshold: ${DB_LEAK_DETECTION:60000}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:5000ms}
      ssl: ${REDIS_SSL:true}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX:25}
          max-idle: ${REDIS_POOL_IDLE:10}
          min-idle: ${REDIS_POOL_MIN:5}
          max-wait: ${REDIS_POOL_WAIT:5000ms}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  cache:
    redis:
      time-to-live: ${CACHE_TTL:1800000} # 30 minutos produção

firebase:
  project-id: ${FIREBASE_PROJECT_ID}
  credentials-path: ${FIREBASE_CREDENTIALS}

vynlo:
  features:
    new-ui: ${FEATURE_NEW_UI:false}
    analytics: ${FEATURE_ANALYTICS:true}
    beta-features: ${FEATURE_BETA:false}
  
  rate-limit:
    requests-per-minute: ${RATE_LIMIT_RPM:300}
    burst-capacity: ${RATE_LIMIT_BURST:30}
  
  cors:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGINS:https://vynlotaste.com,https://admin.vynlotaste.com}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Requested-With
      - X-Request-ID
    allow-credentials: true
    max-age: 3600

  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}
    trust-store: ${SSL_TRUSTSTORE_PATH}
    trust-store-password: ${SSL_TRUSTSTORE_PASSWORD}

  backup:
    enabled: ${BACKUP_ENABLED:true}
    schedule: ${BACKUP_SCHEDULE:0 2 * * *} # 2h da manhã
    retention-days: ${BACKUP_RETENTION:30}
    s3-bucket: ${BACKUP_S3_BUCKET}

logging:
  level:
    com.vynlotaste: ${LOG_LEVEL:INFO}
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: ${LOG_FILE_PATH:/var/log/vynlo-taste/application.log}
    max-size: ${LOG_MAX_SIZE:100MB}
    max-history: ${LOG_MAX_HISTORY:30}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] [%X{traceId:-}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
        step: 30s
    distribution:
      percentiles-histogram:
        http.server.requests: true

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  http2:
    enabled: ${HTTP2_ENABLED:true}