spring:
  application:
    name: vynlo-taste-backend
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:vynlo-postgres-prod}:${DB_PORT:5432}/${DB_NAME:vynlo_taste}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 30000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  redis:
    host: ${REDIS_HOST:vynlo-redis-prod}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2
        max-wait: 3000ms
  
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:false}
    baseline-on-migrate: true
    validate-on-migrate: false
  
  main:
    allow-bean-definition-overriding: ${SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING:true}

# Configurações de monitoramento simplificadas para Docker
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: true
  health:
    redis:
      enabled: true
    db:
      enabled: true
    defaults:
      enabled: true

# Configurações de logging otimizadas para container
logging:
  level:
    root: INFO
    com.vynlotaste: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configurações de segurança
security:
  jwt:
    secret: ${JWT_SECRET:vynloTasteSecretKey2024EnterpriseSystem}
    expiration: ${JWT_EXPIRATION:86400000}
  firebase:
    project-id: ${FIREBASE_PROJECT_ID:vynlo-sistema}
    private-key: ${FIREBASE_PRIVATE_KEY:}
    client-email: ${FIREBASE_CLIENT_EMAIL:}

# Configurações de servidor otimizadas para container
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  tomcat:
    threads:
      max: 100
      min-spare: 10
    max-connections: 2000
    accept-count: 50
    connection-timeout: 10000
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Configurações de CORS para Docker
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:3001
    - https://vynlotaste.com
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600